
spring.datasource.url= jdbc:postgresql://localhost:5432/task_management
spring.datasource.username= postgres
spring.datasource.password= Cloud912345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update


server.address=0.0.0.0
server.port=9090
#
jwt.secret=7854002SecretKeyThatIsLongEnoughForJwtSigningCloudSoft900123456789
jwt.expiration=900000

spring.jpa.properties.hibernate.jdbc.batch_size=300
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

logging.file.name=E:/Task_Management/task-backend/logs/application.log

logging.logback.rollingpolicy.file-name-pattern=E:/Task_Management/task-backend/logs/application-%d{yyyy-MM-dd}.%i.txt

logging.logback.rollingpolicy.max-history=30

logging.logback.rollingpolicy.max-file-size=10MB

logging.logback.rollingpolicy.clean-history-on-start=true